# Notebook destinado a divisão dos dados em treino e teste

## Objetivo

* Dividir os dados em treino e teste para um problema de classificação.
* Etapa anterior ao EDA e a modelagem.

In [ ]:
#Imports
##Bibliotecas
import pandas as pd
import numpy as np
##Eliminar os warnings
import warnings
warnings.filterwarnings("ignore")
##Ver todas as colunas do data frame
pd.set_option('display.max_columns', None)
##Ver todas as linhas do data frame
pd.set_option('display.max_rows', None)
#Divisão da amostra
from sklearn.model_selection import train_test_split

# Visão geral dos dados

In [ ]:
df_final = pd.read_csv("NOME_DO_ARQUIVO.csv", sep = 'XX')
#Visualização
df_final.head(4)

# 1 - Divisão dos dados

In [ ]:
x_m6 = df_final.drop('ALVO', axis=1) #conjunto de variáveis explicativas
y_m6 = df_final['ALVO'] #ALVO

In [ ]:
#A base de treino vai ter 70% dos dados
#A base de teste vai ter 30% dos dados
m6treino_x, m6teste_x, m6treino_y, m6teste_y = train_test_split(x_m6, y_m6, random_state = 1935, test_size = 0.3, stratify = y_m6)

## 1.1 - Base de treino

In [ ]:
#Base de treino completa
df_treino = pd.concat([m6treino_x, m6treino_y], axis=1)
#Visualização
df_treino.head(4)

,num_adm,idade,ag_tempo_base,ag_valor,ag_tipo_cliente,ag_velocidade,meses_base_ultimo_plano,meses_base_cadastro,valor,empresa,cidade,tecnologia,plano,tipo_plano,download,flag_watch,flag_globoplay,valor_watch,valor_globoplay,qt_fat_ab_u0m,qt_fat_ab_u3m,qt_fat_ab_u6m,dias_aberto,flag_compulsorio_m0,flag_compulsorio_u3m,flag_compulsorio_u6m,flag_voluntario_m0,flag_voluntario_u3m,flag_voluntario_u6m,mes_cancelamento,prim_proced_cancelamento_de_contrato,prim_proced_boleto,prim_proced_problema,prim_proced_equipamento,prim_proced_acesso,prim_proced_sinal,prim_proced_senha,prim_proced_retencao,prim_proced_causa,prim_proced_solucao,prim_proced_reclamacao,prim_proced_inatividade,prim_proced_alteracao,prim_proced_conec,prim_proced_conex,prim_proced_tecnic,prim_proced_suporte,prim_proced_lent,prim_proced_desbloq,prim_proced_promo,prim_proced_duvida,prim_proced_queda,prim_proced_golpe,prim_proced_area,prim_proced_instala,ultimo_proced_cancelamento_de_contrato,ultimo_proced_boleto,ultimo_proced_problema,ultimo_proced_equipamento,ultimo_proced_acesso,ultimo_proced_sinal,ultimo_proced_senha,ultimo_proced_retencao,ultimo_proced_causa,ultimo_proced_solucao,ultimo_proced_reclamacao,ultimo_proced_inatividade,ultimo_proced_alteracao,ultimo_proced_conec,ultimo_proced_conex,ultimo_proced_tecnic,ultimo_proced_suporte,ultimo_proced_lent,ultimo_proced_desbloq,ultimo_proced_promo,ultimo_proced_duvida,ultimo_proced_queda,ultimo_proced_golpe,ultimo_proced_area,ultimo_proced_instala,ultimo_proced_cop,qtd_protocolos_u6m,qtd_protocolos_u3m,qtd_protocolos_u0m,qtd_faturas_cobradas_u6m,qtd_faturas_pagas_u6m,qtd_faturas_cobradas_u3m,qtd_faturas_pagas_u3m,qtd_faturas_cobradas_u0m,qtd_faturas_pagas_u0m,media_datediff_u6m,maior_antecedencia_u6m,maior_atraso_u6m,maior_atraso_u3m,maior_antecedencia_u3m,total_cobrado_u6m,total_pago_u6m,media_cobrado_u6m,media_pago_u6m,min_cobrado_u6m,max_cobrado_u6m,min_pago_u6m,max_pago_u6m,total_cobrado_u3m,total_pago_u3m,media_cobrado_u3m,media_pago_u3m,min_cobrado_u3m,max_cobrado_u3m,min_pago_u3m,max_pago_u3m,total_cobrado_u0m,total_pago_u0m,media_cobrado_u0m,media_pago_u0m,min_cobrado_u0m,max_cobrado_u0m,min_pago_u0m,max_pago_u0m,qt_bloqueio_u3m,qt_bloqueio_u0m,qt_bloqueio_u6m,mes_ref,lost_carrier_u6m,lost_carrier_u3m,lost_carrier_u0m,lost_carrier_total,lost_carrier_max,lost_carrier_min,lost_carrier_mes1,lost_carrier_mes2,lost_carrier_mes3,lost_carrier_mes4,lost_carrier_mes5,nas_request_u6m,nas_request_u3m,nas_request_u0m,nas_request_max,nas_request_min,conectado_u6m,conectado_u3m,conectado_u0m,conectado_min,conectado_max,qtd_conexoes_u6m,qtd_conexoes_u3m,qtd_conexoes_u0m,qtd_conexoes_mes1,qtd_conexoes_mes2,qtd_conexoes_mes3,qtd_conexoes_mes4,qtd_conexoes_mes5,diff_conexoes_mes2_mes1,diff_conexoes_mes3_mes2,diff_conexoes_mes4_mes3,diff_conexoes_mes5_mes4,diff_conexoes_mes6_mes5,mudancas_plano_u6m,mudancas_plano_u3m,mudancas_plano_u0m,de_100mb_400mb,de_300mb_900mb,de_500mb_900mb,de_50mb_100mb,de_200mb_600mb,de_200mb_300mb,de_100mb_300mb,de_100mb_600mb,de_100mb_500mb,final_de_desconto_2,final_de_desconto_3,final_de_desconto_4,final_de_desconto_5,final_de_desconto_6,os_u0m,qtd_os_aberta_u0m,qtd_os_cancelada_interrompida_u0m,qtd_finalizadas_u0m,os_u3m,qtd_os_aberta_u3m,qtd_os_cancelada_interrompida_u3m,qtd_finalizadas_u3m,os_u6m,qtd_os_aberta_u6m,qtd_os_cancelada_interrompida_u6m,qtd_os_finalizadas_u6m,descricao_os_ativacao,descricao_os_endereco,descricao_os_migracao,descricao_os_retirada,descricao_os_manutencao,descricao_os_mudanca_de_endereco,qtd_promocao_terminada_u3m,qtd_promocao_terminada_u6m,flag_bloqueio_temporario,flag_funcionario,flag_permuta,flag_cortesia,safra,cluster_perc_pago,cluster_total_pago,cluster_os,cluster_protocolos,cluster_bloqueio,cluster_atraso,pontuacao,cluster,ALVO
4333,3175910,69.0,g_<=36meses,b_<=R$100,pessoa_fisica,a_<=200MB,36.0,36.0,99.90,DSN,S. B. Oeste,Fibra,Fibra Home 300M 2022,T-F-22.300M.4000G,300.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,3.0,2.0,1.0,0.0,-16.833333,-1.0,-41.0,-28.0,-1.0,649.36,431.78,108.23,71.96,99.9,124.88,0.00,125.98,349.66,226.98,116.55,75.66,99.9,124.88,101.00,125.98,124.88,NaN,124.88,NaN,124.88,124.88,NaN,NaN,1.0,0.0,1.0,2212.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,16.0,2.0,1.0,0.0,7.0,3.0,1.0,0.0,1.0,44.0,23.0,4.0,13.0,5.0,3.0,6.0,13.0,-8.0,-2.0,3.0,7.0,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202212,2.0,2.0,4.0,4.0,3.0,1.0,16.0,Baixo Valor,0
106474,843310,34.0,a_<=3meses,c_<=R$120,pessoa_fisica,c_<=650MB,0.0,97.0,116.99,DSN,Sumare,Fibra,Fibra Home 450M 2023 (*),T-F-23.450M.4000G,450000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,3.0,3.0,1.0,1.0,-21.500000,4.0,-28.0,-28.0,4.0,659.40,667.10,109.90,111.18,109.9,109.90,109.90,112.70,329.70,329.70,109.90,109.90,109.9,109.90,109.90,109.90,109.90,109.9,109.90,109.9,109.90,109.90,109.9,109.9,0.0,0.0,0.0,2301.0,49.0,11.0,8.0,49.0,1.0,0.0,8.0,23.0,7.0,0.0,3.0,75.0,40.0,15.0,1.0,0.0,7.0,3.0,1.0,0.0,1.0,138.0,56.0,24.0,27.0,38.0,17.0,15.0,17.0,11.0,-21.0,-2.0,2.0,7.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202301,4.0,3.0,4.0,4.0,4.0,1.0,20.0,Médio Valor,0
9513,6480520,28.0,c_<=9meses,b_<=R$100,pessoa_fisica,a_<=200MB,9.0,9.0,99.90,DSN,Sorocaba,Fibra,Fibra Home Combo 300M 2022,T-G-22.300M.4000G,300.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,3.0,2.0,1.0,0.0,2.333333,14.0,-27.0,-27.0,10.0,599.40,501.20,99.90,83.53,99.9,99.90,99.90,101.60,299.70,201.50,99.90,67.17,99.9,99.90,99.90,101.60,99.90,NaN,99.90,NaN,99.90,99.90,NaN,NaN,0.0,0.0,0.0,2212.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,30.0,18.0,1.0,0.0,6.0,4.0,1.0,0.0,1.0,57.0,40.0,21.0,8.0,5.0,4.0,8.0,11.0,-3.0,-1.0,4.0,3.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,202212,2.0,2.0,3.0,4.0,4.0,1.0,16.0,Baixo Valor,0
147654,7541170,34.0,c_<=9meses,e_>R$120,pessoa_fisica,c_<=650MB,7.0,7.0,129.90,DSN,Piracicaba,Fibra,Fibra Home 600M 2022,T-F-22.600M.4000G,600.000,NaN,NaN,NaN,NaN,1.0,1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,3.0,2.0,1.0,0.0,-28.166667,-23.0,-31.0,-31.0,-31.0,629.40,517.22,104.90,86.20,99.9,129.90,102.92,104.00,329.70,206.92,109.90,68.97,99.9,129.90,102.92,104.00,129.90,NaN,129.90,NaN,129.90,129.90,NaN,NaN,5.0,3.0,8.0,2303.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,40.0,27.0,14.0,1.0,0.0,6.0,3.0,1.0,0.0,1.0,57.0,34.0,15.0,5.0,8.0,10.0,9.0,10.0,3.0,2.0,-1.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,202303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [22]:
#Volumetria
df_treino.shape[0] #117.306

117306

In [23]:
#Frequência do ALVO
round(100 * df_treino['ALVO'].value_counts(True),2) #4.76

0    95.24
1     4.76
Name: ALVO, dtype: float64

### Salvar em CSV

In [24]:
#Salvar em CSV
df_treino.to_csv('df_treino_m6.csv', header=True, index=False, sep=';')

## 1.2 - Base de teste

In [25]:
#Base de treino completa
df_teste = pd.concat([m6teste_x, m6teste_y], axis=1)
df_teste.head(4)

,num_adm,idade,ag_tempo_base,ag_valor,ag_tipo_cliente,ag_velocidade,meses_base_ultimo_plano,meses_base_cadastro,valor,empresa,cidade,tecnologia,plano,tipo_plano,download,flag_watch,flag_globoplay,valor_watch,valor_globoplay,qt_fat_ab_u0m,qt_fat_ab_u3m,qt_fat_ab_u6m,dias_aberto,flag_compulsorio_m0,flag_compulsorio_u3m,flag_compulsorio_u6m,flag_voluntario_m0,flag_voluntario_u3m,flag_voluntario_u6m,mes_cancelamento,prim_proced_cancelamento_de_contrato,prim_proced_boleto,prim_proced_problema,prim_proced_equipamento,prim_proced_acesso,prim_proced_sinal,prim_proced_senha,prim_proced_retencao,prim_proced_causa,prim_proced_solucao,prim_proced_reclamacao,prim_proced_inatividade,prim_proced_alteracao,prim_proced_conec,prim_proced_conex,prim_proced_tecnic,prim_proced_suporte,prim_proced_lent,prim_proced_desbloq,prim_proced_promo,prim_proced_duvida,prim_proced_queda,prim_proced_golpe,prim_proced_area,prim_proced_instala,ultimo_proced_cancelamento_de_contrato,ultimo_proced_boleto,ultimo_proced_problema,ultimo_proced_equipamento,ultimo_proced_acesso,ultimo_proced_sinal,ultimo_proced_senha,ultimo_proced_retencao,ultimo_proced_causa,ultimo_proced_solucao,ultimo_proced_reclamacao,ultimo_proced_inatividade,ultimo_proced_alteracao,ultimo_proced_conec,ultimo_proced_conex,ultimo_proced_tecnic,ultimo_proced_suporte,ultimo_proced_lent,ultimo_proced_desbloq,ultimo_proced_promo,ultimo_proced_duvida,ultimo_proced_queda,ultimo_proced_golpe,ultimo_proced_area,ultimo_proced_instala,ultimo_proced_cop,qtd_protocolos_u6m,qtd_protocolos_u3m,qtd_protocolos_u0m,qtd_faturas_cobradas_u6m,qtd_faturas_pagas_u6m,qtd_faturas_cobradas_u3m,qtd_faturas_pagas_u3m,qtd_faturas_cobradas_u0m,qtd_faturas_pagas_u0m,media_datediff_u6m,maior_antecedencia_u6m,maior_atraso_u6m,maior_atraso_u3m,maior_antecedencia_u3m,total_cobrado_u6m,total_pago_u6m,media_cobrado_u6m,media_pago_u6m,min_cobrado_u6m,max_cobrado_u6m,min_pago_u6m,max_pago_u6m,total_cobrado_u3m,total_pago_u3m,media_cobrado_u3m,media_pago_u3m,min_cobrado_u3m,max_cobrado_u3m,min_pago_u3m,max_pago_u3m,total_cobrado_u0m,total_pago_u0m,media_cobrado_u0m,media_pago_u0m,min_cobrado_u0m,max_cobrado_u0m,min_pago_u0m,max_pago_u0m,qt_bloqueio_u3m,qt_bloqueio_u0m,qt_bloqueio_u6m,mes_ref,lost_carrier_u6m,lost_carrier_u3m,lost_carrier_u0m,lost_carrier_total,lost_carrier_max,lost_carrier_min,lost_carrier_mes1,lost_carrier_mes2,lost_carrier_mes3,lost_carrier_mes4,lost_carrier_mes5,nas_request_u6m,nas_request_u3m,nas_request_u0m,nas_request_max,nas_request_min,conectado_u6m,conectado_u3m,conectado_u0m,conectado_min,conectado_max,qtd_conexoes_u6m,qtd_conexoes_u3m,qtd_conexoes_u0m,qtd_conexoes_mes1,qtd_conexoes_mes2,qtd_conexoes_mes3,qtd_conexoes_mes4,qtd_conexoes_mes5,diff_conexoes_mes2_mes1,diff_conexoes_mes3_mes2,diff_conexoes_mes4_mes3,diff_conexoes_mes5_mes4,diff_conexoes_mes6_mes5,mudancas_plano_u6m,mudancas_plano_u3m,mudancas_plano_u0m,de_100mb_400mb,de_300mb_900mb,de_500mb_900mb,de_50mb_100mb,de_200mb_600mb,de_200mb_300mb,de_100mb_300mb,de_100mb_600mb,de_100mb_500mb,final_de_desconto_2,final_de_desconto_3,final_de_desconto_4,final_de_desconto_5,final_de_desconto_6,os_u0m,qtd_os_aberta_u0m,qtd_os_cancelada_interrompida_u0m,qtd_finalizadas_u0m,os_u3m,qtd_os_aberta_u3m,qtd_os_cancelada_interrompida_u3m,qtd_finalizadas_u3m,os_u6m,qtd_os_aberta_u6m,qtd_os_cancelada_interrompida_u6m,qtd_os_finalizadas_u6m,descricao_os_ativacao,descricao_os_endereco,descricao_os_migracao,descricao_os_retirada,descricao_os_manutencao,descricao_os_mudanca_de_endereco,qtd_promocao_terminada_u3m,qtd_promocao_terminada_u6m,flag_bloqueio_temporario,flag_funcionario,flag_permuta,flag_cortesia,safra,cluster_perc_pago,cluster_total_pago,cluster_os,cluster_protocolos,cluster_bloqueio,cluster_atraso,pontuacao,cluster,ALVO
139566,4818320,54.0,f_<=24meses,e_>R$120,pessoa_fisica,d_<=1GB,22.0,22.0,199.90,DSN,Nova Odessa,Fibra,Fibra Home Combo 600M Mesh 2022 (*),T-G-22.900M.8000G,900.000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,3.0,3.0,1.0,1.0,-8.666667,0.0,-21.0,-21.0,-1.0,1213.54,1229.41,202.26,204.90,199.90,204.48,202.62,207.05,605.10,616.87,201.70,205.62,199.90,203.95,204.49,207.05,201.25,205.33,201.25,205.33,201.25,201.25,205.33,205.33,0.0,0.0,1.0,2303.0,2.0,1.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,29.0,8.0,6.0,1.0,0.0,6.0,3.0,1.0,0.0,1.0,46.0,17.0,9.0,18.0,4.0,7.0,5.0,3.0,-14.0,3.0,-2.0,-2.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202303,4.0,4.0,4.0,4.0,4.0,1.0,21.0,Médio Valor,0
102222,6111010,45.0,a_<=3meses,c_<=R$120,pessoa_fisica,b_<=350MB,0.0,12.0,105.99,DSN,Sumare,Fibra,Fibra Home Combo 350M 2023 (*),T-G-23.350M.4000G,350000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,3.0,3.0,1.0,1.0,-4.166667,11.0,-33.0,-33.0,11.0,601.11,608.91,100.19,101.49,71.61,114.90,75.91,114.90,301.41,305.71,100.47,101.90,71.61,114.90,75.91,114.90,114.90,114.90,114.90,114.90,114.90,114.90,114.90,114.90,4.0,0.0,4.0,2301.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0,32.0,15.0,1.0,0.0,6.0,2.0,1.0,0.0,1.0,65.0,41.0,19.0,3.0,4.0,17.0,11.0,11.0,1.0,13.0,-6.0,0.0,8.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,202301,4.0,3.0,4.0,4.0,1.0,1.0,17.0,Baixo Valor,0
53694,8127840,NaN,h_acima_36meses,c_<=R$120,pessoa_fisica,c_<=650MB,68.0,68.0,109.90,NTL,Jaguariuna,Fibra,Fibra Home 400M 2022 (*),T-F-22.400M.4000G,400.000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,3.0,3.0,1.0,1.0,1.200000,3.0,0.0,0.0,3.0,553.04,553.04,110.61,110.61,109.90,113.44,109.90,113.44,333.24,333.24,111.08,111.08,109.90,113.44,109.90,113.44,113.44,113.44,113.44,113.44,113.44,113.44,113.44,113.44,0.0,0.0,0.0,2302.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,153.0,153.0,102.0,1.0,0.0,2.0,2.0,1.0,0.0,1.0,155.0,155.0,103.0,0.0,0.0,0.0,0.0,52.0,0.0,0.0,0.0,52.0,51.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202302,4.0,3.0,3.0,4.0,4.0,4.0,22.0,Alto Valor,0
135469,983690,48.0,h_acima_36meses,b_<=R$100,pessoa_fisica,b_<=350MB,91.0,91.0,99.90,DSN,Campinas,Fibra,Fibra Home Combo 300M 2022,T-G-22.300M.4000G,300.000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,3.0,3.0,1.0,1.0,-2.833333,2.0,-5.0,-5.0,-2.0,599.40,605.97,99.90,101.00,99.90,99.90,99.90,101.99,299.70,305.87,99.90,101.96,99.90,99.90,101.93,101.99,99.90,101.99,99.90,101.99,99.90,99.90,101.99,101.99,0.0,0.0,0.0,2303.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,11.0,6.0,1.0,0.0,8.0,3.0,1.0,0.0,1.0,47.0,21.0,11.0,11.0,7.0,8.0,6.0,4.0,-4.0,1.0,-2.0,-2.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202303,4.0,3.0,3.0,4.0,4.0,3.0,21.0,Médio Valor,0

In [26]:
#Volumetria
df_teste.shape[0] #50274

50274

In [27]:
#Frequência do ALVO
round(100 * df_teste['ALVO'].value_counts(True),2) #4.77

0    95.23
1     4.77
Name: ALVO, dtype: float64

### Salvar em CSV

In [28]:
#Salvar em CSV
df_teste.to_csv('df_teste_m6.csv', header=True, index=False, sep=';')